#+TITLE: オススメなユーチューブのチャンエル

私はイギリス人でユーチューブが大好きです。これらは、私のお勧めのチャンネルです。どうぞご覧ください。

# * コメディ
# *** Adrian Bliss
# *** College Humor

* ビデオエセー（動画の文章）
*** Jenny Nicholson
主に、彼女の動画は主に何かを馬鹿にしてるものです。好きなテーマはテーマパークやスター・ウォーズや映画です。私の好きな動画は

  オススメな動画：[[https://www.youtube.com/watch?v=YHbtaWr6lj8][There's something wrong with Hallmark's youtube channel]]か[[https://www.youtube.com/watch?v=Nu5bR_89W7U][WHERE’S BUZZY? The Great Animatronic Caper]]
*** HBomberguy
 テーマはふたつ、コンピュタゲームとかテレビについてレビューと バカバカしい人を馬鹿にしてる対応です

 オススメな動画：[[https://youtu.be/0twDETh6QaI][ROBLOX_OOF.mp3]]か[[https://www.youtube.com/watch?v=CnPOQr1pxY8][Halcyon Dreams: The Legacy of Dragon's Lair]]か[[https://www.youtube.com/watch?v=RLqXkYrdmjY][Climate Denial: A Measured Response]]
*** Sarah Z
 主にインタネット文化について文章です

 オススメな動画：[[https://www.youtube.com/watch?v=EeCi4CSqtzw][The Horrifying Panopticon of West Elm Caleb]]
*** Jacob Geller
 彼はもしかしたら世界で一番の話をする能力持ってます。動画は全部素晴らしいと思います

 オススメな動画：[[https://www.youtube.com/watch?v=Pp2wbyLoEtM][Fear of Cold]]か[[https://www.youtube.com/watch?v=JMkrrjKf5AE][Head Transplants and the Non-Existance of the Soul]]
*** Philosophy Tube
Philosophy TubeのAbigailさんは大学生の時で哲学を勉強しました。そして後でユーチューブで哲学のことを説明し初めました。最近、動画はめっちゃ演劇になって素晴らしくします。

オススメな動画：[[https://www.youtube.com/watch?v=d_SYW1ElDb8][The Hidden Rules of Modern Society]]

*** Folding Ideas
  映画関係の仕事しましたから映画制作の知識が深いです。昔でビデオは映画の話ですが、今、色々なテーマがあります。
  オススメな動画：[[https://www.youtube.com/watch?v=YQ_xWvX1n9g][Line Goes Up - The Problem With NFTs]]

* 技術
*** Captain Disillusion
 VFXの専門家は人気な偽物動画を分析します。めっちゃすごい！

 オススメな動画：[[https://www.youtube.com/watch?v=em-pVICrnqM][Marble Sorting Machine DEBUNK]]
*** Michael Reeves
 バカに何かを作ろうとしいて、めっちゃ面白い動画です。例えば、私のススメな動画は「素人が手術のロボット作る」です。

 オススメな動画：[[https://youtu.be/A_BlNA7bBxo][I Built a Surgery Robot]]
# *** Ben Eater
# *** Look Mum No Computer

# * 言語について
# *** Julingo
# *** Langfocus

* 色々
*** Mothcub
 Mothcubはイギリス出身でLilyと呼ぶ芸術家。色んなテーマに面白い動画作ります。私は好きな動画はredditの会話を描いたり音声付いたりするのものです。[[https://www.youtube.com/watch?v=2SjpkBp0RmQ&list=PLoJi7na1AD1kHqNASaQSGKOFn_Qbbxx2y][再生リスト]]

 オススメな動画：[[https://www.youtube.com/watch?v=2SjpkBp0RmQ&list=PLoJi7na1AD1kHqNASaQSGKOFn_Qbbxx2y][I don't want my dead husband's skull]]
*** Super Eyepatch Wolf
このチャンネルは主にアニメとか漫画について話です。そして色んなテーマの動画もあります。例えば[

 オススメな動画：[[https://www.youtube.com/watch?v=m_oeMV2E50A][Why you should watch disturbing horror movies]]
# Tom Scott
# Scottは広くて見られたのユーチューバーです。有名なシリーズは「Things You Might not Know」ですが、語学・コンピューター科学の動画も面白いです。
# 
# スメな動画：
# Computerphile
# リスのノッティンガム大学の講師がコンピューター科学の問題を説明します。その分野で色々な話題は話されましたので、興味があったらみてください！
# Wheezy Waiter
# のチャレーンジのチャンネルです    
# Jay Foreman
# Foremanは音楽使ってコメディアンです。そのほかに、動画の話題は地理学とかロンドンの歴史です。説明のし方はおかしいです
*** Mike Boyd
チャレーンジの動画です。毎回にMikeさんは新たな技能を覚えようとしてます。最初のチャレンジはスケボー出来なくてもキックフリップを覚えたもの。間もなくヒットになりました！

オススメな動画：[[https://www.youtube.com/watch?v=X6iJ0hPpGec][Learn to Break a Glass with Your Voice]]

